text = open('new_state_store.py').read()
text = text.replace("{'': updates}", "{'$set': updates}")
text = text.replace("{'': {'role': role}}", "{'$set': {'role': role}}")
text = text.replace("{'': {'chapters': ch}}", "{'$push': {'chapters': ch}}")
text = text.replace("{'': {'chapters.$.modules': mod}}", "{'$push': {'chapters.$.modules': mod}}")
text = text.replace("{'': {'studentsCount': 1}}", "{'$inc': {'studentsCount': 1}}")
text = text.replace("{'': {'studentsCount': -1}}", "{'$inc': {'studentsCount': -1}}")
text = text.replace("{'': {'progress': progress}}", "{'$set': {'progress': progress}}")
text = text.replace("{'': {'score': score, 'feedback': feedback, 'status': 'graded'}}", "{'$set': {'score': score, 'feedback': feedback, 'status': 'graded'}}")
text = text.replace("{'': {'xp': amount}}", "{'$inc': {'xp': amount}}")
text = text.replace("{'': {'certificates': cert}}", "{'$push': {'certificates': cert}}")
text = text.replace("{'': {'read': True}}", "{'$set': {'read': True}}")
text = text.replace("{'': course_ids}", "{'$in': course_ids}")
text = text.replace("{'': student_ids}", "{'$in': student_ids}")
open('fixed_new_state_store.py', 'w').write(text)
