import React from 'react';
import { Award, BookOpen, Clock } from 'lucide-react';

interface GradeCardPrintProps {
  studentName: string;
  courseTitle: string;
  courseId: string;
  assignments: { title: string; score?: number; grade?: string }[];
  finalScore: number;
  printRef: React.RefObject<HTMLDivElement>;
}

export const GradeCardPrint: React.FC<GradeCardPrintProps> = ({ 
  studentName, 
  courseTitle, 
  courseId,
  assignments, 
  finalScore, 
  printRef 
}) => {
  const dateStr = new Date().toLocaleDateString();

  return (
    <div style={{ display: 'none' }}>
      <div 
        ref={printRef} 
        style={{
          padding: '40px',
          fontFamily: 'sans-serif',
          color: '#111827',
          backgroundColor: '#ffffff',
          width: '800px',
          margin: '0 auto',
          border: '2px solid #e5e7eb',
          borderRadius: '12px'
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #e5e7eb', paddingBottom: '20px', marginBottom: '30px' }}>
          <div>
            <h1 style={{ fontSize: '28px', fontWeight: 'bold', color: '#111827', margin: 0 }}>Official Grade Card</h1>
            <p style={{ color: '#6b7280', margin: '4px 0 0 0' }}>AI Learning Management System</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <p style={{ margin: 0, fontWeight: 'bold' }}>Date Issued: {dateStr}</p>
            <p style={{ margin: '4px 0 0 0', color: '#6b7280' }}>Course ID: {courseId}</p>
          </div>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '10px' }}>Student Information</h2>
          <p style={{ margin: '4px 0', fontSize: '16px' }}><strong>Name:</strong> {studentName}</p>
          <p style={{ margin: '4px 0', fontSize: '16px' }}><strong>Course:</strong> {courseTitle}</p>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '15px' }}>Academic Performance</h2>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ backgroundColor: '#f3f4f6', borderBottom: '2px solid #d1d5db' }}>
                <th style={{ padding: '12px', textAlign: 'left', fontWeight: 'bold' }}>Assignment</th>
                <th style={{ padding: '12px', textAlign: 'center', fontWeight: 'bold' }}>Grade</th>
                <th style={{ padding: '12px', textAlign: 'right', fontWeight: 'bold' }}>Score (%)</th>
              </tr>
            </thead>
            <tbody>
              {assignments.map((assignment, index) => (
                <tr key={index} style={{ borderBottom: '1px solid #e5e7eb' }}>
                  <td style={{ padding: '12px' }}>{assignment.title}</td>
                  <td style={{ padding: '12px', textAlign: 'center' }}>{assignment.grade || '-'}</td>
                  <td style={{ padding: '12px', textAlign: 'right' }}>{assignment.score != null ? `${assignment.score}%` : 'Pending'}</td>
                </tr>
              ))}
              {assignments.length === 0 && (
                <tr>
                  <td colSpan={3} style={{ padding: '20px', textAlign: 'center', color: '#6b7280' }}>No assignments recorded.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '20px' }}>
          <div style={{ backgroundColor: '#f9fafb', padding: '20px', borderRadius: '8px', border: '1px solid #e5e7eb', width: '300px' }}>
            <h3 style={{ margin: '0 0 10px 0', fontSize: '16px', color: '#4b5563' }}>Final Overall Score</h3>
            <div style={{ fontSize: '36px', fontWeight: 'bold', color: '#4f46e5' }}>
              {finalScore}%
            </div>
            <p style={{ margin: '10px 0 0 0', fontSize: '14px', color: '#6b7280' }}>
              {finalScore >= 90 ? 'Excellent Performance' : finalScore >= 75 ? 'Good Performance' : finalScore >= 60 ? 'Satisfactory' : 'Needs Improvement'}
            </p>
          </div>
        </div>

        <div style={{ marginTop: '60px', borderTop: '1px solid #e5e7eb', paddingTop: '20px', display: 'flex', justifyContent: 'space-between' }}>
          <div>
            <p style={{ margin: 0, color: '#6b7280', fontSize: '12px' }}>Generated by AI-LMS Automated Grading System</p>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ borderBottom: '1px solid #111827', width: '200px', marginBottom: '8px' }}></div>
            <p style={{ margin: 0, fontSize: '14px', color: '#374151' }}>Authorized Signature</p>
          </div>
        </div>
      </div>
    </div>
  );
};
